name: Quality Gates

on:
  pull_request:
    branches: [main]

jobs:
  enforce-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check test coverage threshold
        run: npm run test:coverage

      - name: Verify no TypeScript errors
        run: npm run typecheck

      - name: Verify no ESLint errors
        run: npm run lint

      - name: Check for forbidden patterns
        run: |
          echo "Checking for 'any' type usage..."
          if grep -r ": any" src/ --include="*.ts" | grep -v ".test.ts"; then
            echo "ERROR: Found 'any' type usage (forbidden)"
            exit 1
          fi

          echo "Checking for console.log usage..."
          if grep -r "console\.log" src/ --include="*.ts" | grep -v ".test.ts"; then
            echo "WARNING: Found console.log usage (should be removed)"
          fi

      - name: Validate file size limits
        run: |
          echo "Enforcing 500-line limit per file..."
          violations=0
          while IFS= read -r file; do
            lines=$(wc -l < "$file")
            if [ $lines -gt 500 ]; then
              echo "ERROR: $file has $lines lines (max 500)"
              violations=$((violations + 1))
            fi
          done < <(find src -name "*.ts" -type f)

          if [ $violations -gt 0 ]; then
            echo "FAILED: $violations file(s) exceed 500-line limit"
            exit 1
          fi
          echo "PASSED: All files under 500 lines"
